## Linear algebra
##### Linear algebra is the branch of mathematics that deals with vector spaces.
Source: Data Science From Scratch, chapter 4.

##### 7 important concepts we will work with are:
1. **scalar values** a single value like 5 or 8
2. **vectors** (List of (mostly) numbers. The four common types of atomic vector are logical, integer, double (sometimes called numeric), and character)
  - Vectors can represent attributes of an entity (like age,weight,height of a person)
  - vectors has magnitude (size of each attribute) and direction (coeficient of the line starting in 0,0,...)
2. **matrices** (matrix in plural) 2 dimensional list of numbers (list of vectors) or (one-hot-encoded relationships between x and y axis)
3. **vector space** (the n-dimensional coordinate system in which the vectors can move around)
4. **vector arithmetics** (addition, substraction, division and multiplication of vectors with vectors and vectors with scalars)
5. **dot products** sum of products of all elements of 2 vectors resulting in single value
6. **matrix products** 2 matrices joined to one where each row element from one matrix multiplied by each column element in another matrix summed up in each cell of the resulting matrix


## Basic math understanding
This notebook is providing the necessary base understanding for working with **feature spaces in machine learning**

## Vector operations

The vectors we will use, are list of numbers, and you can do a number of things with them!


In [1]:
import numpy as np

In [2]:
scalar = 7

v = np.array([1, 5, 8, -2, 6])

In [3]:
v.shape

(5,)

In [4]:
np.array([[1], [5], [8], [-2], [0]]).shape

(5, 1)

In [5]:
np.array([[1, 3], [0]]).shape

(2,)

In [6]:
np.array([1,2,3,4,5]).reshape(-1,1) # equals: np.array([1,2,3,4,5]).reshape(5,1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [7]:
v.reshape(-1, 1) == v.reshape(5,1)

array([[ True],
       [ True],
       [ True],
       [ True],
       [ True]])

### Vector - scalar operations

In [8]:
# Addition
v + scalar

array([ 8, 12, 15,  5, 13])

In [9]:
# Subtraction
v - scalar

array([-6, -2,  1, -9, -1])

In [10]:
# Division
v / scalar

array([ 0.14285714,  0.71428571,  1.14285714, -0.28571429,  0.85714286])

In [11]:
# Multiplication
v * scalar

array([  7,  35,  56, -14,  42])

### Vector - vector operations

In [12]:
v = np.array([1, 5, 8, -2, 6])
p = np.array([2, 1, -1])

In [13]:
v + v

array([ 2, 10, 16, -4, 12])

## The vector is an object which has both the magnitude as well as direction
![](images/vector_addition.svg)

In [14]:
# ValueError vectors of different dimensions can not be added together
try:
    v + p
except Exception as e:
    print(e)

operands could not be broadcast together with shapes (5,) (3,) 


In [15]:
v - v

array([0, 0, 0, 0, 0])

In [16]:
v / v

array([1., 1., 1., 1., 1.])

In [17]:
try:
    v * p
except Exception as e:
    print(e)

operands could not be broadcast together with shapes (5,) (3,) 


## Vector dot product
See this [reference](https://www.mathsisfun.com/algebra/vectors-dot-product.html)

### Magnitude of a vector 
The vector is an object which has both the magnitude as well as direction. To find the magnitude of a vector, we need to calculate the length of the vector.   

This is calculated as squareroot of (the sum of each feature squared)
$\sqrt(\sum(v1^2 + v2^2 + vn^2))$

### Distance between 2 vectors
is calculated as difference between each feature squared then summed and then the squareroot of that
$\sqrt((v1-w1)^2 + (v2-w2)^2 + (vn-wn)^2)$

## Matrix 
A matrix is a 2 dimensional data structure like a list a of lists b where b are all of same length   
One Matrix, Two Matrices
A matrix can be thought of as a **list of vectors**
In this respect it is very well suited for representing a feature space like a list of persons or a list of test runs on a new chemical compound etc.

##  Matrix operations:

Math: $v = \begin{bmatrix} -2 & 0 & 1 \\ 5 & -4 & 2 \\ 7 & -1 & 3\end{bmatrix}$

Python:
```python
m = np.array([[-2, 0, 1], [5, -4, 2], [7, -1, 3]])
```

In [18]:
import numpy as np
scalar = 7
v = np.array([2, 0, -1])

m = np.array([[-2, 0, 1], [5, -4, 2], [7, -1, 3]])
print('type of v',type(v),'\ntype of m:',type(m))
print(scalar,'\nvector:',v,'\nmatrix:\n',m)

type of v <class 'numpy.ndarray'> 
type of m: <class 'numpy.ndarray'>
7 
vector: [ 2  0 -1] 
matrix:
 [[-2  0  1]
 [ 5 -4  2]
 [ 7 -1  3]]


In [19]:
m.shape

(3, 3)

### Matrix - scalar operations

In [20]:
import numpy as np
scalar_value = np.array(3)
vector = np.array([3,4])
matrix = np.array([[3,4],[4,5]])
print('Dimensions of a scalar: ',scalar_value.ndim)
print('Dimensions of a vector: ',vector.ndim)
print('Dimensions of a matrix: ',matrix.ndim)

Dimensions of a scalar:  0
Dimensions of a vector:  1
Dimensions of a matrix:  2


In [21]:
m + scalar # Addition

array([[ 5,  7,  8],
       [12,  3,  9],
       [14,  6, 10]])

In [22]:
m - scalar # Subtraction

array([[ -9,  -7,  -6],
       [ -2, -11,  -5],
       [  0,  -8,  -4]])

In [23]:
m / scalar # Division

array([[-0.28571429,  0.        ,  0.14285714],
       [ 0.71428571, -0.57142857,  0.28571429],
       [ 1.        , -0.14285714,  0.42857143]])

In [24]:
m * scalar # Multiplication

array([[-14,   0,   7],
       [ 35, -28,  14],
       [ 49,  -7,  21]])

### Matrix - vector operations

In [25]:
print("Matrix: \n", m)
print("\nVector: \n", v)

Matrix: 
 [[-2  0  1]
 [ 5 -4  2]
 [ 7 -1  3]]

Vector: 
 [ 2  0 -1]


In [26]:
#v = np.array([2, 0, -1, 5]) # to provoce a ValueError: operands could not be broadcast together with shapes

In [27]:
m + v

array([[ 0,  0,  0],
       [ 7, -4,  1],
       [ 9, -1,  2]])

In [28]:
m - v

array([[-4,  0,  2],
       [ 3, -4,  3],
       [ 5, -1,  4]])

In [29]:
print("Matrix: \n", m)
print("Vector: ", p)

Matrix: 
 [[-2  0  1]
 [ 5 -4  2]
 [ 7 -1  3]]
Vector:  [ 2  1 -1]


In [30]:
m / p

array([[-1. ,  0. , -1. ],
       [ 2.5, -4. , -2. ],
       [ 3.5, -1. , -3. ]])

In [31]:
m * p # Note, this is NOT called matrix multiplication!!! Matrix multiplication is using the dot product see here: https://www.mathsisfun.com/algebra/matrix-multiplying.html

array([[-4,  0, -1],
       [10, -4, -2],
       [14, -1, -3]])

In [32]:
print("Matrix: \n", m)
print("Vector: ", v)

Matrix: 
 [[-2  0  1]
 [ 5 -4  2]
 [ 7 -1  3]]
Vector:  [ 2  0 -1]


### Matrix - matrix operations

In [33]:
m = np.array([[-2, 0, 1], [5, -4, 2], [7, -1, 3]])

In [34]:
m.shape

(3, 3)

In [35]:
m + m

array([[-4,  0,  2],
       [10, -8,  4],
       [14, -2,  6]])

In [36]:
m - m

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [37]:
m / m

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[ 1., nan,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [38]:
m * m # Note, this is NOT matrix multiplication

array([[ 4,  0,  1],
       [25, 16,  4],
       [49,  1,  9]])

### Entry-wise product, Hadamard product
Is not a matrix product (see further down)

![](https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Hadamard_product_qtl1.svg/220px-Hadamard_product_qtl1.svg.png)

In [56]:
m = np.array([[-2, 0, 1], [5, -4, 2], [7, -1, 3]])
q = np.array([[0, 7], [-3, 2], [1, 5]])
print('m:\n',m,'\nq:\n',q,'\nm shape: ',m.shape,'\nq shape: ',q.shape)

m:
 [[-2  0  1]
 [ 5 -4  2]
 [ 7 -1  3]] 
q:
 [[ 0  7]
 [-3  2]
 [ 1  5]] 
m shape:  (3, 3) 
q shape:  (3, 2)


In [42]:
try:
    m + q
except Exception as e:
    print(e)

operands could not be broadcast together with shapes (3,3) (3,2) 


In [43]:
try:
    m * q
except Exception as e:
    print(e)

operands could not be broadcast together with shapes (3,3) (3,2) 


In [44]:
np.matmul(m, q)

array([[ 1, -9],
       [14, 37],
       [ 6, 62]])

### Matrix multiplication
**Requirement:** A's number of collumns equals to B's number of rows

![](https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Matrix_multiplication_diagram_2.svg/313px-Matrix_multiplication_diagram_2.svg.png)

##### [matrix multiplication example](https://www.mathsisfun.com/algebra/matrix-multiplying.html)

## Exercise Matrix multiplication

Multiply the following matrix `m.dot(q)` by hand:
```python
m = np.array([[-2, 0, 1], [5, -4, 2], [7, -1, 3]])
q = np.array([[0, 7], [-3, 2], [1, 5]])
```

In [45]:
m.dot(q)
# q.dot(m) #ValueError: shapes (3,2) and (3,3) not aligned:

array([[ 1, -9],
       [14, 37],
       [ 6, 62]])

In [46]:
print(q.shape)
q.T.shape

(3, 2)


(2, 3)

## Matrix transpose

![](https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Matrix_transpose.gif/200px-Matrix_transpose.gif)

In [47]:
a = np.array([[-2, 5], [0, 4]])
b = np.array([0, 7])

In [48]:
np.arange(12).reshape(3, 4).T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [49]:
m.T

array([[-2,  5,  7],
       [ 0, -4, -1],
       [ 1,  2,  3]])

In [50]:
q = np.array([[0, 7], [-3, 2], [1, 5]])

In [51]:
q.shape

(3, 2)

In [52]:
q.T.shape

(2, 3)

## Real life example using the matrix multiplication
Building on this source: https://www.mff.cuni.cz/veda/konference/wds/proc/pdf06/WDS06_106_m8_Ulrychova.pdf

Three persons p1,p2,p3 wants to buy some apples, bananas, clementines and eggplants. Each person wants to buy differing amounts and can buy them in two different shops S1, S2.
Which shop is the best for each person p1, p2, p3 to pay as little as possible?  
The individual prices and desired quantities of the commodities are given in the following tables:

**Needed fruits and veggies**  

|person|apple|banana|clementine|eggplant|
|--|--|--|--|--|
|p1|6|5|3|1|
|p2|3|6|2|2|
|p3|3|4|3|1|

**Prices in the 2 shops**  

|merchandise|S1| S2|
|--|--|--|
|apples|1.50| 1.00|
|bananas |2.00| 2.50|
|clementines |5.00 |4.50|
|eggplants |16.00 |17.00|

For example, the amount spent by the **person p1** would be:  
**Shop s1**: `6 · 1.50 + 5 · 2.00 + 3 · 5.00 + 1 · 16.00 = 50`  
**Shop s2**: `6 · 1.00 + 5 · 2.50 + 3 · 4.50 + 1 · 17.00 = 49`

**The 2 metrices would look like this:**

```
P = [[6,5,3,1],
     [3,6,2,2],
     [3,4,3,1]]
``` 
and  
```
Q = [[1.50,  1.00],
     [2.00,  2.50],
     [5.00,  4.50],
     [16.00, 17.00]]
``` 
The matrix product looks like this
```
R = PQ = [[50.00, 49.00],
          [58,50, 61.00],
          [43.50, 43.50]]
```
|persons|shop 1 sum of prod|shop 2 sum of prod|
|--|--|--|
|p1|50.00|49.00|
|p2|58.50|61.00|
|p3|43.50|43.50|

##### Conclusion:
person 1 should go to shop 2  
person 2 should go to shop 1 and  
person 3 can go to either shop  


In [53]:
# Above calculation done with numpy:

import numpy as np
P = np.array([[6,5,3,1],
     [3,6,2,2],
     [3,4,3,1]])
Q = np.array([[1.50,  1.00],
     [2.00,  2.50],
     [5.00,  4.50],
     [16.00, 17.00]])
R = P.dot(Q)
R

array([[50. , 49. ],
       [58.5, 61. ],
       [43.5, 43.5]])

## Class exercise
Given the below dictionarys find out where each of the 4 people find the cheapest shopping according to their needs.
```python
shoppers = {
'Paula':{'Is':4,'Juice':2,'Kakao':3,'Lagkager':2},
'Peter':{'Is':2,'Juice':5,'Kakao':0, 'Lagkager':4},
'Pandora':{'Is':5,'Juice':3, 'Kakao':4, 'Lagkager':5},
'Pietro':{'Is':1,'Juice':8, 'Kakao':9, 'Lagkager':1}
}
shop_prices = {
    'Netto': {'Is':10.50,'Juice':2.25,'Kakao':4.50,'Lagkager':33.50},
    'Fakta': {'Is':4.00,'Juice':4.50,'Kakao':6.25,'Lagkager':20.00}
}
```
Hint: you can use pandas and Transpose to create dataframe: `pd.DataFrame(shoppers).T` to get the necessary shape of the dataframe/matrix. Also use df.to_numpy() to changes a Pandas DataFrame df into a numpy ndarray with only the numeric data
